### ISSUE TITLE
[Analysis] Impact of CPU on the Response Time

### ISSUE THREAD

**Issue by danielfireman** [vtex/reliability-research#100]
After running an experiment and collecting metrics, one thing we need is to understand how the CPU utilization impacts the response time

## Reminder
First things to do

1. **Read about correlation and read the paper we published at CloudCom 2018**: even though is focused on GC, this paper might give you ideas about what to look for and how to present the impact. 
    - Pro-Tip: Look at the histogram tail, mean and median might not show much
1. Describe a plan of action: what are you going to look? How? Any idea about the stats?

## Verification

A 7 minute presentation about the results

**Comment by dfquaresma** [comment]
Hi @danielfireman, @gabialverga and I agree that our next move must go in the following direction:
- We will perform an **experiment** to evaluate the impact of the CPU usage on the request's latency
- Our **hypothesis** will be that the CPU usage and the request latency are correlated.
- We wanna start using as **workload** the downsampled one, but with the canonical one targeted in mind.
- We will not vary the factors of the **independent variables** here. We plan to use the SOLR Cloud as it is already set and run the Replayer with 512 number of goroutines.
- As **dependent variables**, we'll use the requests' latency and the Solr's JVMs CPU usage as metrics.
- To begin, we want to test those two variables running a **correlation test** and **plotting a scatterplot**.
- With the scripts as they are now, we know how much CPU was used in a period between two timestamps. We also know the timestamp of each request. Said so, we think that we can **categorize each request to a CPU consume based on its timestamp**.

**Comment by danielfireman** [comment]
> We wanna start using as workload the downsampled one, but with the canonical one targeted in mind.

Why? If would like to evaluate CPU, why get less load?

> With the scripts as they are now, we know how much CPU was used in a period between two timestamps. We also know the timestamp of each request. Said so, we think that we can categorize each request to a CPU consume based on its timestamp.

Not clear, could you please clarify?

**Comment by gabialverga** [comment]
Hi @danielfireman, 
- Why? If would like to evaluate CPU, why get less load?
We will perform this test because we didn't run with canonical load yet and the downsamples one it a canonical with a reduced load.

**Comment by dfquaresma** [comment]
> Not clear, could you please clarify?

The scripts as we have today give us two sorts of information we require:

- About requests' latency, we have the timestamp and latency of each request generated during experiments.
- About the CPU, we have a little more complex data. We have the timestamp and usage (in seconds) of CPU by all Solr's JVMs. This data is cumulative, so, the CPU usage value in some timestamp has the CPU usage of the last timestamp in it.

The second one (about CPU) may be useful if we remove the cumulative aspect in such a way that every CPU usage in some timestamps corresponds to the use of CPU since the last timestamp. With that kind of data, we can classify our requests by its timestamp associated. For example:

- Consider that we have CPU usage of timestamp A and C, only. Every request in timestamp between A and C will receive the CPU usage of the timestamp C because the usage in timestamp refers to the CPU usage since timestamp A.

I think that's a viable approach once that in a context where we could have a CPU usage to each request, every CPU usage data would be almost (cause there are other kinds of JVM CPU consume in) the consume of each request

**Comment by dfquaresma** [comment]
@thiagomanel could you also verify our plan?

**Comment by thiagomanel** [comment]
Sorry if it is too late, but I think this experiment is not sound (maybe, I have little context to say so). As @dfquaresma and @gabialverga wrote: 
> We will perform an experiment to evaluate the impact of the CPU usage on the request's latency

it seems, by this description, that you guys/gals are planning to have the CPU usage as knob (as an independent variable). Then, you are going to change it to observe the effect on the request latency. But the remaining of the description of the experiment says something different. 

Maybe, we can evolve faster in this discussion if you people tell me the whys behind this experiment. Why is it important to understand the relation (maybe causal, maybe not) between latency and cpu utilization. If needed, poke me to have a conf call.

**Comment by dfquaresma** [comment]
Hi @thiagomanel, in a call with @danielfireman, we clear the main points of this study but we didn't update this issue yet. 

The main goal, as the title, is to investigate the CPU impact on request latency. I think we might do this study to understand how the limitation of the resources may impact service quality. Another motivation is that we are attacking all possible performance bottleneck

The experiment and analysis suggested are poorly explained. As a result of the call that I mention, we decide to evaluate the relation between CPU and request latency in a better way: we are going to focus on periods of time and do the analysis based on the intervals of CPU metrics collections. 

We know, as said, the CPU usage of a given timestamp since the last timestamp of it. What we are also going to do is collapse the request latencies to something like that. We may look to metrics such as median ou 99 percentile of those latencies and compare them with the CPU usage. Thus, we are going to generate a plot with the x-axes representing time and two y-axes, one representing the CPU usage and another the request latency observed (the metrics that represents the request latency in the period selected)

We shall give more details and plot examples in the future, very soon.

Thanks!

**Comment by thiagomanel** [comment]
Thanks for the clarification @dfquaresma. Still related to the objective:

> The main goal, as the title, is to investigate the CPU impact on request latency

Just as a remark, I have the feeling that it would be hard to understand the effect of the CPU utilization on the latency in this design unless we control de CPU utilization (e.g by adding a controlled, background load). As you said, there is more context to understand the case. I'll track this in the group meetings

**Comment by dfquaresma** [comment]
Last Friday when @gabialverga and I were evaluating the results obtained and performing a sanity check to verify if the results make sense, we face that we do not understand completely the CPU metrics that we are studying.

During the sanity check, we analyzed the total time of CPU usage of the JVM of Solr instances. We note that this value may reach 75 seconds. Once each collect happens between every 0.5 seconds, and that every node has 16 vCPUs, and we have 4 nodes, without hyperthreading and considering that the JVM would be at the CPU running all time, we would have a maximum of 32 seconds of usage. 

Since the docs we have found 'til here just says that the time is the total time used by the Sorl's JVM, we can't say if the results seen in the sanity check refers to some problem during the experiments or a lack of information about the variable.

**Comment by dfquaresma** [comment]
Another problem we had when analyzing the results was the scale of the output. The median of the response time of requests is 16ms and the median of the CPU usage time of JVM is 56s.  We didn't improve our plots to visualize it better.

**Comment by dfquaresma** [comment]
> Since the docs we have found 'til here just says that the time is the total time used by the Sorl's JVM, we can't say if the results seen in the sanity check refers to some problem during the experiments or a lack of information about the variable.

About the lack of information about the metrics we are collecting, we decide to upgrade the way we collect the metrics of CPU. We are going to "ask" this information directly from the UNIX.

**Comment by dfquaresma** [comment]
I have an idea about how to retrieve these data from the Linux interface using only uptime and some grep.  The following links I'm based in.

- https://linuxconfig.org/how-to-check-and-monitor-cpu-utilization-on-linux
- https://www.tecmint.com/understand-linux-load-averages-and-monitor-performance/
- http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html

My idea is to retrieve the average load of CPU usage of the last one minute at each CPU metrics collection. I'm searching if this value is only updated after 1 minute or if it represents the usage of the last 1 minute since the time where the uptime command was executed (which is what I think I need).

**Comment by dfquaresma** [comment]
Analysis aborted
